#include<stdio.h>
#include<stdlib.h>
#include<iostream.h>// librerias
#include<conio.h>
#include<string.h>
#include<fstream.h>
#include<ctype.h>

 void main()
 {
 cout<<"                    ESCUELA SUPERIOR POLITECNICA DEL CHIMBORAZO  "<<endl;
 cout<<endl;
      cout<<"                            LENGUAJE DE PROGRAMACION        "<<endl;

      cout<<endl;

      cout<<"                                 SEGUNDO A                  "<<endl;

      cout<<endl;

      cout<<"                  |-----------PROYECTO FINAL------------|"<<endl;
		cout<<"                  |-------------------------------------|"<<endl;
		cout<<"                  |                                     |"<<endl;
		cout<<"                  |      INTEGRANTES:       CODIGO:     |"<<endl;
		cout<<"                  |                                     |"<<endl;
		cout<<"                  |     Arellano Dario       789        |"<<endl;
		cout<<"                  |                                     |"<<endl;
		cout<<"                  |     Eder Naranjo         695        |"<<endl;
		cout<<"                  |                                     |"<<endl;
		cout<<"                  |     Rosa  Sanchez        605        |"<<endl;
		cout<<"                  |                                     |"<<endl;
		cout<<"                  |-------------------------------------|"<<endl;
		cout<<endl;
       system("pause");
		 system("cls");    // rosiita   ss s s  s s 



 getch();
 }

